### PR TITLE
Code Review

### PR DESCRIPTION
**Pull request by roshii**
Some other easy fix

### CODE REVIEW

**Comment by stepansnigirev** [comment]
Awesome! Thanks!

**Comment by stepansnigirev** [comment]
FIY, I am currently rewriting the wallet to use libwally & libsecp256k1 and refactoring wallet architecture in general, so don't spend too much time on the core functionality yet...

**Comment by roshii** [comment]
Thanks for the heads up.
So far I am simply getting familiar with MbedOS/STM32 platform and C/C++, learning to interact with internal storage and playing around with GUI. I did try for a couple hours to fix some issue I notice with `root.fingerprint()` but gotta catch-up on basics first!
In short, I'm not ready to dive into core functions, yet :D

Real nice project btw, thanks!

**Comment by stepansnigirev** [comment]
Thanks!
With `root.fingerprint()` I forgot to bump uBitcoin version, so just git pull to the latest version of the library - it has this functionality now.

**Comment by roshii** [comment]
> just git pull to the latest version of the library - it has this functionality now.

Yeah !!! I have a home made hardware wallet :)
I'll continue learning and try to contribute as soon as refactoring is published

Enjoy your weekend

**Pull request merged**
